In [2]:
# import the necessary libraries
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [ ]:
# Define the state space
states = ["CP", "IP"]
n_states = len(states)
print('Number of hidden states :',n_states)
# Define the observation space
observations = ["Cola", "ice_t","lem"]    #cola, iced_tea, lemonade are expected observations
n_observations = len(observations)
print('Number of observations  :',n_observations)

Number of hidden states : 2
Number of observations  : 3


In [ ]:
n_layers= n_states+1
print("No of layers in HMM: ",n_layers)

No of layers in HMM:  3


In [ ]:
# Define the initial state distribution
state_probability = np.array([1.0, 0.0])      # pi values of state
print("State probability: ", state_probability)

# Define the state transition probabilities
transition_probability = np.array([[0.7, 0.3],       #row sum always 1 in this matrix
                                   [0.5, 0.5]])
print("\nTransition probability:\n", transition_probability)
# Define the observation likelihoods
emission_probability= np.array([[0.6,  0.1, 0.3],
                                 [0.1, 0.7, 0.2]])
print("\nEmission probability:\n", emission_probability)

State probability:  [1. 0.]

Transition probability:
 [[0.7 0.3]
 [0.5 0.5]]

Emission probability:
 [[0.6 0.1 0.3]
 [0.1 0.7 0.2]]


In [ ]:
cola=0
ice_tea=1
lem=2
op_seq=[2,1,0]    #to be derived= lem,ice_tea,cola
new =[1,1]

In [ ]:
def forward_prop(state_probability,transition_probability,emission_probability):
    for i in range(n_layers):
        a_cp=0
        a_ip=0
        for j in range(2):
            a_cp+= ((state_probability[j]) * (transition_probability[j][0]) * (emission_probability[j][op_seq[i]]) )
            a_ip+= (state_probability[j]* transition_probability[j][1]* emission_probability[j][op_seq[i]])
        state_probability[0]=a_cp
        state_probability[1]=a_ip
        print(a_cp)
        print(a_ip)

    tot_prob= a_cp+a_ip
    print("TOTAL PROBABILITY: ", tot_prob)

forward_prop(state_probability,transition_probability,emission_probability)


0.21
0.09
0.0462
0.0378
0.021293999999999993
0.010206
TOTAL PROBABILITY:  0.03149999999999999


In [ ]:
# Define the state transition probabilities
transition_probability = np.array([[0.7, 0.3],       #row sum always 1 in this matrix
                                   [0.5, 0.5]])
print("\nTransition probability:\n", transition_probability)
# Define the observation likelihoods
emission_probability= np.array([[0.6,  0.1, 0.3],
                                 [0.1, 0.7, 0.2]])
print("\nEmission probability:\n", emission_probability)


Transition probability:
 [[0.7 0.3]
 [0.5 0.5]]

Emission probability:
 [[0.6 0.1 0.3]
 [0.1 0.7 0.2]]


In [ ]:
cola=0
ice_tea=1
lem=2
op_seq=[2,1,0]    #to be derived= lem,ice_tea,cola
new =[1,1]

In [ ]:
def backward_prop(new,transition_probability,emission_probability):
    k=2
    for i in range(n_layers):
        b_cp=0    #initialization
        b_ip=0
        for j in range(2):
            b_cp+= ((new[j]) * (transition_probability[0][j]) * (emission_probability[0][op_seq[k]]))
            #print(j, " ", b_cp)
            b_ip+= (new[j] * transition_probability[1][j] * emission_probability[1][op_seq[k]])
            #print(j," ", b_ip)
        k=k-1
        new[0]=b_cp
        new[1]=b_ip
        print(b_cp)
        print(b_ip)

    tot_prob= b_cp*state_probability[0]+b_ip*state_probability[1]
    print("TOTAL PROBABILITY: ",tot_prob)

backward_prop(new,transition_probability,emission_probability)

0.6
0.1
0.045000000000000005
0.245
0.0315
0.029
TOTAL PROBABILITY:  0.0009667349999999998
